language: android
dist: trusty
sudo: false

env:
  global:
  - ANDROID_HOME=/usr/local/android-sdk

android:
  components:
    - tools
    - android-29
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager 'cmake;3.6.4111459' >/dev/null
  - echo y | sdkmanager 'ndk;16.1.4479499' >/dev/null
  - gem install bundler
  - gem update --system 3.0.6
  - bundle install
  - ls $ANDROID_HOME

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

jobs:
  include:
    # Unit test job
    - name: unit tests
      script: ./gradlew check

    # Plugin install job
    - name: plugin install
      script: ./gradlew build install -x groovyDoc -x codenarcMain -x codenarcTest --stacktrace

    # AGP 3.4.0 E2E tests
    - name: AGP 3.4.0 E2E tests
      env:
        - APP_FIXTURE_DIR=features/fixtures/app_agp340
        - RN_FIXTURE_DIR=features/fixtures/rnapp_agp340/android
        - NDK_FIXTURE_DIR=features/fixtures/ndkapp_agp340
      script: bundle exec maze-runner features/agp3-features features/agp-features -c --verbose

    # AGP 4.0.0 E2E tests
    - name: AGP 4.0.0 E2E tests
      script: bundle exec maze-runner features/agp4-features features/agp-features -c --verbose
