language: android
dist: trusty
sudo: false

env:
  global:
  - ANDROID_HOME=/usr/local/android-sdk
  - NDK_VERSION=r16b

android:
  components:
    - tools
    - android-29
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager 'cmake;3.6.4111459'
  - gem install bundler
  - gem update --system 3.0.6
  - bundle install
  - ls $ANDROID_HOME
  - ./install_ndk.sh

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs

script:
  - ./gradlew check
  - ./gradlew clean install -x groovyDoc -x codenarcMain -x codenarcTest --stacktrace
  - ./gradlew clean build -x groovyDoc -x codenarcMain -x codenarcTest --stacktrace
  - bundle exec maze-runner -c --verbose

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
