steps:
#  - label: 'Audit current licenses'
#    timeout_in_minutes: 30
#    plugins:
#      - docker-compose#v3.7.0:
#          run: license-audit

  - label: ':docker: Build Android gradle plugin CI image'
    key: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-gradle-plugin-ci-v8
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
            - android-gradle-plugin-ci-v8:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-gradle-plugin-ci-v8
      - docker-compose#v3.7.0:
          push:
            - android-gradle-plugin-ci-v8:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:android-gradle-plugin-ci-v8

  - label: ':android: Detekt'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci-v8
          command: ['./gradlew', 'detekt']

  - label: ':android: Ktlint'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci-v8
          command: ['./gradlew', 'ktlintCheck']

  - label: ':android: Unit tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci-v8
          command: ['./gradlew', 'test']

  - label: ':android: AGP 8.0.0 E2E tests'
    depends_on: 'agp-ci'
    timeout_in_minutes: 60
    plugins:
      - docker-compose#v3.7.0:
          run: android-gradle-plugin-ci-v8
          env:
            - AGP_VERSION=8.0.0-beta02
            - GRADLE_WRAPPER_VERSION=8.0
            - RN_FIXTURE_DIR=features/fixtures/rn070/android
          command: ['bundle', 'exec', 'maze-runner', '-c', '--verbose', '--fail-fast']
